### ISSUE TITLE
Record ID number of parents if the child/neonate who has no ID number

### ISSUE THREAD

**Issue by hangl9** [rward3182/Shanghai#14]

**Comment by rward3182** [comment]
- we don't collect this information In the Philippines. Are there questions in the gen module that are used in other countries and also, how would we analyse this information?

**Comment by rward3182** [comment]
New problem: logic not working if no stills asks the question.

**Comment by rward3182** [comment]
This is needed is the relevance column on the "Record  the National ID number:" question
selected(${gen_6_6}, '1')
This is saying the "Record  the National ID number:" question is **only** asked if the answer to 
gen_6_6 | Did the decedent have a   National ID number? **Is yes (1)**
