### ISSUE TITLE
Test Shanghai form output after Mandarin Changes

### ISSUE THREAD

**Issue by rward3182** [rward3182/Shanghai#2]

**Comment by rward3182** [comment]
Hang has been testing. Found 11 issues suspect most pre existing.

**Comment by rward3182** [comment]
Tested and it apparently works. For some reason needed to re add --Chinese to power-shell script.
Did the snake bite one. Handing to Hang Li for further testing.

**Comment by hangl9** [comment]
hello roger

**Comment by rward3182** [comment]
Hang has tested and looks OK. May nee more test cases. Marked as closed but can reopen
